# Generated by Django 2.1.4 on 2019-01-16 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='remarks',
            new_name='remark',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 22, 2, 16, 958651, tzinfo=utc)),
        ),
    ]
